# Generated by Django 6.0.4 on 2026-04-25 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_carpeta', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestada', 'Prestada'), ('extraviada', 'Extraviada')], default='disponible', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('nombre_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ambiente')),
            ],
        ),
        migrations.AddField(
            model_name='carpeta',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante'),
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('estante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estante')),
            ],
        ),
        migrations.AddField(
            model_name='carpeta',
            name='piso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.piso'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_limite_devolucion', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autoridad')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carpeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidente', models.CharField(max_length=50)),
                ('fecha_reporte', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plazo_reposicion_dias', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Prorroga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField()),
                ('nueva_fecha_limite', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autoridad')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contenido', models.TextField(blank=True, null=True)),
                ('usuario_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('administrativo', 'Administrativo'), ('externo', 'Externo')], max_length=50)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estudiante_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitante'),
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_bloqueo', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_desbloqueo_manual', models.DateField(blank=True, null=True)),
                ('autoridad_desbloqueo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.autoridad')),
                ('prestamo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestamo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
