# Generated by Django 6.0.4 on 2026-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='carpeta',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='carpetas',
            field=models.ManyToManyField(related_name='prestamos', to='api.carpeta'),
        ),
    ]
