# Generated by Django 6.0.4 on 2026-05-08 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prestamocarpeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueo',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
