# Generated by Django 6.0.4 on 2026-05-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bloqueo_persona_persona_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='usuario',
        ),
    ]
