# Generated by Django 5.2 on 2026-05-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
