# Generated by Django 5.2 on 2026-05-15 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_perfil_is_2fa_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devol', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('prestamo_carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestamocarpeta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
