# Generated by Django 5.2 on 2026-05-16 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_carpeta_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ubicado', models.BooleanField(default=False)),
                ('ambiente_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_destino', to='api.ambiente')),
                ('ambiente_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_origen', to='api.ambiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraspasoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicado', models.BooleanField(default=False)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.carpeta')),
                ('piso_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.piso')),
                ('traspaso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.traspaso')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='api.ambiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'ambiente')},
            },
        ),
    ]
