# Generated by Django 5.2 on 2026-05-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_traspaso_traspasocarpeta_asignacionambiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('gestionar_carpetas', 'Gestionar Carpetas'), ('gestionar_documentos', 'Gestionar Documentos'), ('gestionar_prestamos', 'Gestionar Préstamos'), ('gestionar_devoluciones', 'Gestionar Devoluciones'), ('gestionar_traspasos', 'Gestionar Traspasos'), ('gestionar_ubicaciones', 'Gestionar Ubicaciones'), ('gestionar_personas', 'Gestionar Personas'), ('gestionar_bloqueos', 'Gestionar Bloqueos'), ('ver_dashboard', 'Ver Dashboard y Reportes')]},
        ),
    ]
