# Generated by Django 5.2 on 2026-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_temptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='estado_devolucion',
            field=models.CharField(default='buen_estado', max_length=20),
        ),
    ]
