# Generated by Django 5.2 on 2026-05-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_devolucion_estado_devolucion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('gestionar_carpetas', 'Gestionar Carpetas'), ('gestionar_documentos', 'Gestionar Documentos'), ('gestionar_prestamos', 'Gestionar Préstamos'), ('gestionar_devoluciones', 'Gestionar Devoluciones'), ('gestionar_traspasos', 'Gestionar Traspasos'), ('gestionar_ubicaciones', 'Gestionar Ubicaciones'), ('gestionar_personas', 'Gestionar Personas'), ('gestionar_bloqueos', 'Gestionar Bloqueos'), ('gestionar_prorrogas', 'Gestionar Prórrogas'), ('gestionar_usuarios', 'Gestionar Usuarios'), ('ver_dashboard', 'Ver Dashboard y Reportes')]},
        ),
    ]
