# Generated by Django 5.2 on 2026-05-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_perfil_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='temptoken',
            name='purpose',
            field=models.CharField(choices=[('2fa', '2FA Verification'), ('reset', 'Password Reset')], default='2fa', max_length=10),
        ),
    ]
