# Generated by Django 5.2 on 2026-05-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_temptoken_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='session_invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
