# Generated by Django 5.2 on 2026-05-26 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_perfil_session_invalidated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='prorroga',
            old_name='dias_solicit',
            new_name='dias_otorgados',
        ),
        migrations.RenameField(
            model_name='prorroga',
            old_name='fecha_solici',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='prorroga',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='prorroga',
            name='fecha_aprobado',
        ),
        migrations.AddField(
            model_name='prorroga',
            name='persona_solicita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.persona'),
        ),
        migrations.AddField(
            model_name='prorroga',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
