# Generated by Django 5.2 on 2026-05-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_prorroga_model_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piso',
            name='capacidad_max',
        ),
        migrations.AddField(
            model_name='estante',
            name='limite_pisos',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
