# Generated by Django 5.2 on 2026-05-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_piso_capacidad_max_estante_limite_pisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='propietario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estante',
            name='limite_pisos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
